imports:
    - { resource: services/forms/*.yml }
    - { resource: services/transformer/*.yml }
    - { resource: services/*.yml }

services:

    # tool installer
    form_builder.tool.installer:
        class: FormBuilderBundle\Tool\Install

    # tool: file locator
    form_builder.tool.file_locator:
        class: FormBuilderBundle\Tool\FileLocator
        arguments:
            - '@filesystem'

    # configuration
    form_builder.configuration:
        class: FormBuilderBundle\Configuration\Configuration

    # session: configurator
    form_builder.session.configurator:
        class: FormBuilderBundle\Session\SessionConfigurator
        tags:
            - { name: pimcore.session.configurator }

    # area brick
    form_builder.area.brick.form:
        class: FormBuilderBundle\Document\Areabrick\Form\Form
        arguments:
            - '@session'
            - '@form_builder.manager.form'
            - '@form_builder.manager.preset'
            - '@form_builder.form_builder'
            - '@form_builder.manager.template'
            - '@pimcore.translator'
        tags:
            - { name: pimcore.area.brick, id: formbuilder_form }

    # factory: form
    form_builder.factory.form:
        class: FormBuilderBundle\Factory\FormFactory
        arguments:
            - '@pimcore.translator'

    # registry: options transformer
    form_builder.registry.options_transformer:
        class: FormBuilderBundle\Registry\OptionsTransformerRegistry
        arguments:
            - FormBuilderBundle\Transformer\OptionsTransformerInterface

    #parser: mail
    form_builder.parser.mail:
        shared: false
        class: FormBuilderBundle\Parser\MailParser
        arguments:
            - '@templating'
            - '@form_builder.form_values_beautifier'

    # alias for formbuilder subscriber.
    form_builder.event_subscriber.builder:
        alias: FormBuilderBundle\EventSubscriber\FormBuilderSubscriber
        public: true

    # form builder
    form_builder.form_builder:
        class: FormBuilderBundle\Form\Builder
        arguments:
            - '@form_builder.event_subscriber.builder'
            - '@form_builder.configuration'
            - '@request_stack'
            - '@form_builder.manager.form'
            - '@form.factory'
            - '@router'

    #form values beatuifier
    form_builder.form_values_beautifier:
        class: FormBuilderBundle\Form\FormValuesBeautifier
        arguments:
            - '@pimcore.translator'

    # backend form builder
    form_builder.backend.form_builder:
        class: FormBuilderBundle\Backend\Form\Builder
        arguments:
            - '@form_builder.configuration'
            - '@form_builder.manager.template'
            - '@pimcore.translator'
            - '@form_builder.registry.options_transformer'