form_builder:
    types:
        text:
            class: Symfony\Component\Form\Extension\Core\Type\TextType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.text_type'
                icon_class: 'form_builder_icon_text'
        textarea:
            class: Symfony\Component\Form\Extension\Core\Type\TextareaType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.textarea_type'
                icon_class: 'form_builder_icon_textarea'
        integer:
            class: Symfony\Component\Form\Extension\Core\Type\IntegerType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.integer_type'
                icon_class: 'form_builder_icon_integer'
        checkbox:
            class: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.checkbox_type'
                icon_class: 'form_builder_icon_checkbox'
        submit:
            class: Symfony\Component\Form\Extension\Core\Type\SubmitType
            backend:
                form_type_group: buttons
                label: 'form_builder_type.submit_type'
                icon_class: 'form_builder_icon_button'
                constraints: false
                fields:
                    options.required: ~
                    optional.email_label: ~
                    options.data: ~
        choice:
            class: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            backend:
                form_type_group: choice_fields
                label: 'form_builder_type.choice_type'
                icon_class: 'form_builder_icon_multi_select'
                fields:
                    options.expanded:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.expanded'
                        config: ~
                    options.multiple:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.multiple'
                        config: ~
                    options.choices:
                        display_group_id: attributes
                        type: key_value_repeater
                        label: 'form_builder_type_field.choices'
                        options_transformer: 'form_builder.options_transformer.choices'
                        config: ~