form_builder:
    backend_field_type_config:
        textarea_type:
            form_type_group: text_fields
            label: 'form_builder_type.textarea_type'
            icon_class: 'form_builder_icon_textarea'
            tabs: ~
            display_groups: ~
            fields: ~