form_builder:
    backend_field_type_config:
        text_type:
            form_type_group: text_fields
            icon_class: 'form_builder_icon_text'
            tabs: ~
            display_groups: