form_builder:
    types:
        text:
            class: Symfony\Component\Form\Extension\Core\Type\TextType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.text_type'
                icon_class: 'form_builder_icon_text'
                fields:
                    options.value: ~
        hidden:
            class: Symfony\Component\Form\Extension\Core\Type\HiddenType
            backend:
                form_type_group: hidden_fields
                label: 'form_builder_type.hidden_type'
                icon_class: 'form_builder_icon_hidden'
                fields:
                    options.value: ~
                    options.help_text: ~
        textarea:
            class: Symfony\Component\Form\Extension\Core\Type\TextareaType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.textarea_type'
                icon_class: 'form_builder_icon_textarea'
                fields:
                    options.value: ~
        integer:
            class: Symfony\Component\Form\Extension\Core\Type\IntegerType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.integer_type'
                icon_class: 'form_builder_icon_integer'
                fields:
                    options.value: ~
        checkbox:
            class: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.checkbox_type'
                icon_class: 'form_builder_icon_checkbox'
                fields:
                    options.data:
                        display_group_id: base
                        type: checkbox
                        label: 'form_builder_type_field_base.data'
                        config: ~
        submit:
            class: Symfony\Component\Form\Extension\Core\Type\SubmitType
            backend:
                form_type_group: buttons
                label: 'form_builder_type.submit_type'
                icon_class: 'form_builder_icon_button'
                constraints: false
                fields:
                    optional.email_label: ~
                    options.help_text: ~
                    options.data: ~
                    options.value: ~
        dynamic_multi_file:
            class: FormBuilderBundle\Form\Type\DynamicMultiFileType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.dynamic_multi_file'
                icon_class: 'form_builder_icon_file'
                fields:
                    options.data: ~
                    options.value: ~
                    options.allowed_extensions:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.allowed_extensions'
                        config: ~
                    options.allowed_extensions_label:
                        display_group_id: attributes
                        type: label
                        label: 'form_builder_type_field.allowed_extensions_desc'
                    options.max_file_size:
                        display_group_id: attributes
                        type: textfield
                        label: 'form_builder_type_field.max_file_size'
                        config: ~
                    options.max_file_size_label:
                        display_group_id: attributes
                        type: label
                        label: 'form_builder_type_field.max_file_size_desc'
        html_tag:
            class: FormBuilderBundle\Form\Type\HtmlTagType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.html_tag_type'
                icon_class: 'form_builder_icon_html_tag'
                constraints: false
                fields:
                    optional.email_label: ~
                    options.help_text: ~
                    options.data: ~
                    options.value: ~
                    options.tag:
                        display_group_id: attributes
                        type: select
                        label: 'form_builder_type_field.tag_element'
                        config:
                            options: '%form_builder_html_tag_elements%'
        snippet:
            class: FormBuilderBundle\Form\Type\SnippetType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.snippet_type'
                icon_class: 'form_builder_icon_snippet_tag'
                constraints: false
                fields:
                    optional.email_label: ~
                    options.help_text: ~
                    options.data: ~
                    options.value: ~
                    options.path:
                        display_group_id: attributes
                        type: href
                        label: 'form_builder_type_field.snippet_path'
                        config:
                            types:
                                - 'document'
                            subtypes:
                                document:
                                    - 'snippet'
        choice:
            class: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            backend:
                form_type_group: choice_fields
                label: 'form_builder_type.choice_type'
                icon_class: 'form_builder_icon_multi_select'
                fields:
                    options.value: ~
                    options.data:
                        display_group_id: base
                        type: tagfield
                        label: 'form_builder_type_field_base.data'
                        config: ~
                    options.expanded:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.expanded'
                        config: ~
                    options.multiple:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.multiple'
                        config: ~
                    options.placeholder:
                        display_group_id: attributes
                        type: textfield
                        label: 'form_builder_type_field.placeholder'
                        options_transformer: FormBuilderBundle\Transformer\DefaultValueTransformer
                        config:
                            default_value: false
                    options.placeholder_label:
                        display_group_id: attributes
                        type: label
                        label: 'form_builder_type_field.placeholder_desc'
                    options.choices:
                        display_group_id: attributes
                        type: key_value_repeater
                        label: 'form_builder_type_field.choices'
                        options_transformer: FormBuilderBundle\Transformer\ChoicesTransformer
                        config: ~