services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # factory: form
    FormBuilderBundle\Factory\FormFactoryInterface: '@FormBuilderBundle\Factory\FormFactory'
    FormBuilderBundle\Factory\FormFactory: ~