services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

     # stream: files
    FormBuilderBundle\Stream\FileStream: ~

     # stream: packages
    FormBuilderBundle\Stream\PackageStream: ~