services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FormBuilderBundle\Twig\Extension\StaticFormExtension:
        tags:
            - { name: twig.extension }