services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Validator\Constraints\DynamicMultiFileNotBlankValidator:
        tags:
            - { name: validator.constraint_validator }