form_builder:
    area:
        presets: []

    form:
        templates:
            -
                value: 'form_div_layout.html.twig'
                key: 'form_div_layout'
                default: false
            -
                value: 'bootstrap_3_layout.html.twig'
                key: 'bootstrap_3_layout'
                default: true
            -
                value: 'bootstrap_3_horizontal_layout.html.twig'
                key: 'bootstrap_3_horizontal_layout'
                default: false
        field:
            templates:
                -
                    value: default
                    key: 'Default'
                    default: true
    admin:
        active_elements:
            fields: []


imports:
    - { resource: backend/form_type/*.yml }